### ISSUE TITLE
Will design the website with css and javascript

### ISSUE THREAD

**Issue by Souvik34** [SuchitReddi/cybersentinel#11]
Redesign the structure of the website without changing any functionality

**Comment by SuchitReddi** [comment]
Hi @Souvik34 , you're welcome to contribute! Please join the communication channel for further communication.

**Comment by VineeTagarwaL-code** [comment]
assign me please

**Comment by VineeTagarwaL-code** [comment]
![image](https://github.com/SuchitReddi/cybersentinel/assets/91052168/0b885a24-95e5-4916-8e41-dbed8acabd54)
@SuchitReddi

**Comment by SuchitReddi** [comment]
The UI for cyber sentinel can be found after installing the web application by following these steps: https://suchitreddi.github.io/cybersentinel/docs/setupw.html

It looks like this:
![image0.png](https://github.com/SuchitReddi/cybersentinel/assets/72243194/4cb0b458-a356-45cd-9590-5f1ebdcededc)

And it can be found here:
cybersentinel/sentinel/css/main.css
