### ISSUE TITLE
codeofconduct

### ISSUE THREAD

**Issue by pinak22dhir** [SuchitReddi/cybersentinel#9]
u can add codeofconduct file? can u assign this to me???

**Comment by SuchitReddi** [comment]
Sure @pinak22dhir ! I am grateful for your willingness to contribute. I made this project mostly for self-learning purposes, which is why such official documentation is missing.

**Comment by pinak22dhir** [comment]
pls assign this to me, so that i can do further prs @SuchitReddi

**Comment by SuchitReddi** [comment]
Please join the slack or discord channel for any more communication. You can find the links in readme.

**Comment by pinak22dhir** [comment]
@SuchitReddi kindly add kwoc tag on the issue
